
// Initial database seed data

const users = [
  {
    id: "3958dc9e-712f-4377-85e9-fec4b6a6442a",
    name: "John Doe",
    email: "joedoe@nextmail.com",
    password: "123456",
    image_url: "/users/john-doe.png",
  },
  {
    id: "3958dc9e-742f-4377-85e9-fec4b6a6442a",
    name: "Mary Smith",
    email: "marysmith@nextmail.com",
    password: "789123",
    image_url: "/users/mary-smith.png",
  },
  {
    id: "3958dc9e-737f-4377-85e9-fec4b6a6442a",
    name: "Jane Robinson",
    email: "jane@nextmail.com",
    password: "456789",
    image_url: "/users/jane-robinson.png",
  },
];

const artisans = [
  {
    id: "50ca3e18-62cd-11ee-8c99-0242ac120002",
    name: "Aisha Al-Farsi",
    email: "aisha@nextmail.com",
    password: "333444",
    story: "Each thread carries the weight of a story, woven together for generations.",
    image_url: "/images/aisha_al_farsi.jpg",
    studio_name: "Silk Road Weavers",
    craft_type: "Textiles",
  },
  {
    id: "3958dc9e-787f-4377-85e9-fec4b6a6442a",
    name: "Julian Vance",
    email: "julian@nextmail.com",
    password: "567555",
    story: "Sustainability is found in the longevity of timeless, well-crafted design.",
    image_url: "/images/julian_vance.jpg",
    studio_name: "Minimalist Metals",
    craft_type: "Jewelry",
  },
  {
    id: "76d65c26-f784-44a2-ac19-586678f7c2f2",
    name: "Elena Rossi",
    email: "elena@nextmail.com",
    password: "999999",
    story: "My work is a conversation between the ancient earth and modern aesthetics.",
    image_url: "/images/elena_rossi.jpg",
    studio_name: "Earth & Fire Studio",
    craft_type: "Ceramics",
  },
  {
    id: "d6e15727-9fe1-4961-8c5b-ea44a9bd81aa",
    name: "Marcus Thorne",
    email: "liambaker@nextmail.com",
    password: "888888",
    story: "I listen to the grain of the wood to find the hidden form within each piece.",
    image_url: "/images/marcus_thorne.jpg",
    studio_name: "Grain & Soul",
    craft_type: "Woodworking",
  },
  {
    id: "126eed9c-c90c-4ef6-a4a8-fcf7408d3c66",
    name: "Clara Dupont",
    email: "william@nextmail.com",
    password: "876876",
    story: "Colors harvested from the garden, woven for your home.",
    image_url: "/images/clara_dupont.jpg",
    studio_name: "Loom & Leaf",
    craft_type: "Textiles",
  },
  {
    id: "c0ca3e18-62cd-11ee-8c99-0242ac120002",
    name: "Oliver Schmidt",
    email: "oliver@nextmail.com",
    password: "111222",
    story: "Built to endure, designed to age beautifully with use.",
    image_url: "/images/oliver_schmidt.jpg",
    studio_name: "Iron & Hide",
    craft_type: "Leatherwork",
  },
];

const items = [
  {
    id: "65836928-49b3-499a-a1d3-4437f2397efd",
    artisan_id: artisans[0].id,
    title: "Dream Catcher",
    price: 6000,
    category: "textiles",
    description: "Beautiful pink dream catcher.",
    image_url: "/arts/textile-dream.png",
    status: "available",
  },
  {
    id: "aedc7eda-1bd6-4579-ad15-0e975417b9a9",
    artisan_id: artisans[0].id,
    title: "Hammock",
    price: 20000,
    category: "textiles",
    description: "Handmade hammock with detailed craftsmanship.",
    image_url: "/arts/textile-hammock.png",
    status: "available",
  },
  {
    id: "5c92efa6-adc4-4e58-94f0-c961b3965de9",
    artisan_id: artisans[0].id,
    title: "Purse",
    price: 10000,
    category: "textiles",
    description: "Colorful purse for multiple occasions.",
    image_url: "/arts/textile-purse.png",
    status: "available",
  },
  {
    id: "db5e7412-0841-459e-befd-dc88deca86c2",
    artisan_id: artisans[0].id,
    title: "Straw Mat",
    price: 8000,
    category: "textiles",
    description: "Decorative straw mat for indoor and outdoor use.",
    image_url: "/arts/textile-straw-carpet.png",
    status: "available",
  },

  {
    id: "178c98fb-e191-478c-81b7-8188e3d1b254",
    artisan_id: artisans[1].id,
    title: "Bracelet Collection",
    price: 2000,
    category: "accessories",
    description: "Adjustable bracelets with colorful designs.",
    image_url: "/arts/accessories-bracelets.png",
    status: "available",
  },
  {
    id: "185a0416-c325-464a-aedc-cd78ed870a9a",
    artisan_id: artisans[1].id,
    title: "Purple Earrings",
    price: 3000,
    category: "accessories",
    description: "Elegant purple handmade earrings.",
    image_url: "/arts/accessories-earrings-purple.png",
    status: "available",
  },

  {
    id: "3f9c667a-2357-40b5-9313-bb76724cfefc",
    artisan_id: artisans[2].id,
    title: "Cabana",
    price: 40000,
    category: "art",
    description: "Painting inspired by childhood vacations.",
    image_url: "/arts/art-cabana.png",
    status: "available",
  },
  {
    id: "c0e150e4-c010-40fa-8732-220e5ec2b3ba",
    artisan_id: artisans[2].id,
    title: "Ocean",
    price: 30000,
    category: "art",
    description: "Abstract ocean painting inspired by peace.",
    image_url: "/arts/art-ocean.png",
    status: "available",
  },

  {
    id: "bfc40419-a440-49d6-a157-0389ef606501",
    artisan_id: artisans[3].id,
    title: "Decorative Pillow",
    price: 3000,
    category: "decor",
    description: "Modern decorative throw pillow.",
    image_url: "/arts/decor-pillow.png",
    status: "available",
  },

  {
    id: "2dc6b2f9-0154-48f1-82cf-4621fef537bf",
    artisan_id: artisans[4].id,
    title: "Birds",
    price: 60000,
    category: "art",
    description: "Art inspired by freedom and nature.",
    image_url: "/arts/art-birds.png",
    status: "available",
  },
];

const reviews = [
  {
    user_id: users[0].id,
    item_id: items[1].id,
    text: "Amazing quality and very comfortable hammock.",
    date: "2024-01-12",
    rate: 5,
  },
  {
    user_id: users[1].id,
    item_id: items[4].id,
    text: "Beautiful bracelet and excellent craftsmanship.",
    date: "2024-02-20",
    rate: 4,
  },
  {
    user_id: users[2].id,
    item_id: items[7].id,
    text: "The painting looks incredible in my office.",
    date: "2024-03-15",
    rate: 5,
  },
];

module.exports = {
  users,
  artisans,
  items,
  reviews,
};

